api_platform:
    title: 'API title'
    description: 'API description'
    version: '0.0.0'
    show_webby: true
    name_converter: ~
    path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'
    allow_plain_identifiers: false
    doctrine:
        enabled: true
    eager_loading:
        enabled: true
        fetch_partial: false
        max_joins: 30
        force_eager: true
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    enable_entrypoint: true
    enable_docs: true
    enable_profiler: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    enable_nelmio_api_doc: true
